Fix typo in Example Inline Template section
There's a typo inside `my_inline_job` on step `my_inline_command` parameter which causes `circleci config process` to return:

```
Error: Error calling workflow: 'build-test-deploy'
Error calling job: 'inline_example/my_inline_job'
Error calling command: 'my_inline_command'
Missing required argument(s): greeting_name
```

The step `my_inline_command` should receive `greeting_name` parameter in order to work properly:

```
        steps:
          - my_inline_command:
              greeting_name: <<parameters.greeting_name>>
```